apiVersion: "pravega.pravega.io/v1beta1"
kind: "PravegaCluster"
metadata:
  name: {{ template "pravega.fullname" . }}
  labels:
    app.kubernetes.io/name: "pravega-cluster"
spec:
  version: {{ .Values.version }}
  zookeeperUri: {{ .Values.zookeeperUri }}
  externalAccess:
    enabled: {{ .Values.externalAccess.enabled }}
    type: {{ .Values.externalAccess.type }}
  bookkeeperUri: {{ .Values.bookkeeperUri }}
  pravega:
    {{- if .Values.externalAccess.enabled }}
    controllerServiceAccountName: {{ .Values.serviceAccount.name }}
    segmentStoreServiceAccountName: {{ .Values.serviceAccount.name }}
    {{- end }}
    image:
      repository: {{ .Values.pravega.image.repository }}
    controllerReplicas: {{ .Values.pravega.controllerReplicas }}
    controllerResources:
      requests:
        memory: "1Gi"
        cpu: "1000m"
      limits:
        memory: "2Gi"
        cpu: "2000m"
    segmentStoreReplicas: {{ .Values.pravega.segmentStoreReplicas }}
    segmentStoreResources:
      limits:
        cpu: {{ .Values.pravega_resources.segment_store.limits.cpu }}
        memory: {{ .Values.pravega_resources.segment_store.limits.memory }}
      requests:
        cpu: {{ .Values.pravega_resources.segment_store.requests.cpu }}
        memory: {{ .Values.pravega_resources.segment_store.requests.memory }}
    segmentStoreJVMOptions:
        {{- if .Values.segmentStoreJVMOptions }}
{{ toYaml .Values.segmentStoreJVMOptions | indent 6 }}
        {{- end }}
    debugLogging: {{ .Values.pravega.debugLogging }}
    cacheVolumeClaimTemplate:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.pravega.storage.className }}
      resources:
        requests:
          storage: {{ .Values.pravega.cacheVolumeRequest }}
    options:
      bookkeeper.bkEnsembleSize: "3"
      bookkeeper.bkWriteQuorumSize: "3"
      bookkeeper.bkAckQuorumSize: "3"
      bookkeeper.bkWriteTimeoutMillis: "60000"
      bookkeeper.maxOutstandingBytes: "33554432"
      pravegaservice.cacheMaxSize: "10737418240"
      pravegaservice.cacheMaxTimeSeconds: "600"
      writer.flushThresholdBytes: "67108864"
      writer.maxFlushSizeBytes: "67108864"
      pravegaservice.containerCount: "48"
      controller.containerCount: "48"
      controller.retention.bucketCount: "8"
      controller.service.asyncTaskPoolSize: "20"
      controller.retention.threadCount: "4"
      log.level: "DEBUG"
      metrics.dynamicCache.size: "100000"
      metrics.statistics.enable: "true"
      metrics.statsD.reporter.enable: "true"
      metrics.statsD.connect.host: "telegraph.default"
      metrics.statsD.connect.port: "8125"
      metrics.influxDB.reporter.enable: "true"
      metrics.influxDB.connect.uri: "http://192.168.219.39:8086"
      metrics.influxDB.connect.db.name: "pravega"
      metrics.influxDB.retention: "two_hour"
      metrics.output.frequency.seconds: "10"
      controller.metrics.dynamicCache.size: "100000"
      controller.metrics.statistics.enable: "true"
      controller.metrics.statsD.reporter.enable: "true"
      controller.metrics.statsD.connect.host: "telegraph.default"
      controller.metrics.statsD.connect.port: "8125"
      controller.metrics.influxDB.reporter.enable: "true"
      controller.metrics.influxDB.connect.uri: "http://192.168.219.39:8086"
      controller.metrics.influxDB.connect.db.name: "pravega"
      controller.metrics.influxDB.retention: "two_hour"
      controller.metrics.output.frequency.seconds: "10"
    longtermStorage:
      filesystem:
        persistentVolumeClaim:
          claimName: {{ .Values.pravega.longtermStorage }}
