apiVersion: "pravega.pravega.io/v1beta1"
kind: "PravegaCluster"
metadata:
  name: {{ template "pravega.fullname" . }}
  labels:
    app.kubernetes.io/name: "pravega-cluster"
spec:
  version: {{ .Values.version }}
  zookeeperUri: {{ .Values.zookeeperUri }}
  externalAccess:
    enabled: {{ .Values.externalAccess.enabled }}
    type: {{ .Values.externalAccess.type }}
  bookkeeperUri: {{ .Values.bookkeeperUri }}
  pravega:
    {{- if .Values.externalAccess.enabled }}
    controllerServiceAccountName: {{ .Values.serviceAccount.name }}
    segmentStoreServiceAccountName: {{ .Values.serviceAccount.name }}
    {{- end }}
    image:
      repository: {{ .Values.pravega.image.repository }}
    controllerReplicas: {{ .Values.pravega.controllerReplicas }}
    controllerResources:
      requests:
        memory: "1Gi"
        cpu: "1000m"
      limits:
        memory: "2Gi"
        cpu: "2000m"
    segmentStoreReplicas: {{ .Values.pravega.segmentStoreReplicas }}
    segmentStoreResources:
      limits:
        cpu: {{ .Values.pravega_resources.segment_store.limits.cpu }}
        memory: {{ .Values.pravega_resources.segment_store.limits.memory }}
      requests:
        cpu: {{ .Values.pravega_resources.segment_store.requests.cpu }}
        memory: {{ .Values.pravega_resources.segment_store.requests.memory }}
    segmentStoreJVMOptions:
        {{- if .Values.segmentStoreJVMOptions }}
{{ toYaml .Values.segmentStoreJVMOptions | indent 6 }}
        {{- end }}
    debugLogging: {{ .Values.pravega.debugLogging }}
    cacheVolumeClaimTemplate:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.pravega.storage.className }}
      resources:
        requests:
          storage: {{ .Values.pravega.cacheVolumeRequest }}
    longtermStorage:
      ecs:
        configUri:  {{ .Values.pravega.longtermStorage.configUri }}
        bucket: {{  .Values.pravega.longtermStorage.bucket }}
        prefix: {{ .Values.pravega.longtermStorage.prefix }}
        credentials: {{ .Values.pravega.longtermStorage.credentials }}
