apiVersion: "pravega.pravega.io/v1beta1"
kind: "PravegaCluster"
metadata:
  name: {{ template "pravega.fullname" . }}
  labels:
    app.kubernetes.io/name: "pravega-cluster"
spec:
  version: {{ .Values.version }}
  zookeeperUri: {{ .Values.zookeeperUri }}
  externalAccess:
    enabled: {{ .Values.externalAccess.enabled }}
    type: {{ .Values.externalAccess.type }}
  bookkeeperUri: {{ .Values.bookkeeperUri }}
  pravega:
    {{- if .Values.externalAccess.enabled }}
    controllerServiceAccountName: {{ .Values.serviceAccount.name }}
    segmentStoreServiceAccountName: {{ .Values.serviceAccount.name }}
    {{- end }}
    image:
      repository: {{ .Values.pravega.image.repository }}
    controllerReplicas: {{ .Values.pravega.controllerReplicas }}
    controllerResources:
      requests:
        memory: "1Gi"
        cpu: "1000m"
      limits:
        memory: "2Gi"
        cpu: "2000m"
    segmentStoreReplicas: {{ .Values.pravega.segmentStoreReplicas }}
    segmentStoreResources:
      limits:
        cpu: {{ .Values.pravega_resources.segment_store.limits.cpu }}
        memory: {{ .Values.pravega_resources.segment_store.limits.memory }}
      requests:
        cpu: {{ .Values.pravega_resources.segment_store.requests.cpu }}
        memory: {{ .Values.pravega_resources.segment_store.requests.memory }}
    segmentStoreJVMOptions:
        {{- if .Values.segmentStoreJVMOptions }}
{{ toYaml .Values.segmentStoreJVMOptions | indent 6 }}
        {{- end }}
    debugLogging: {{ .Values.pravega.debugLogging }}
    cacheVolumeClaimTemplate:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.pravega.storage.className }}
      resources:
        requests:
          storage: {{ .Values.pravega.cacheVolumeRequest }}
    options:
      bookkeeper.ensemble.size: "3"
      bookkeeper.write.quorum.size: "3"
      bookkeeper.ack.quorum.size: "3"
      pravegaservice.storage.layout: "ROLLING_STORAGE"
      storage.appends.enable: "true"
      bookkeeper.write.timeout.milliseconds: "60000"
      bookkeeper.write.outstanding.bytes.max: "33554432"
      pravegaservice.cache.size.max: "1073741824"
      pravegaservice.cache.time.seconds.max: "600"
      writer.flush.threshold.bytes: "67108864"
      writer.flush.size.bytes.max: "67108864"
      pravegaservice.container.count: "32"
      controller.containerCount: "32"
      controller.retention.bucketCount: "8"
      controller.service.asyncTaskPoolSize: "20"
      controller.retention.threadCount: "4"
      log.level: "INFO"
      metrics.dynamicCache.size: "2000"
      metrics.statistics.enable: "true"
      metrics.statsD.reporter.enable: "false"
      metrics.statsD.connect.host: "10.109.190.185"
      metrics.statsD.connect.port: "8125"
      metrics.influxDB.reporter.enable: "true"
      metrics.influxDB.connect.uri: "http://192.168.246.24:8086"
      metrics.influxDB.connect.db.name: "pravega"
      metrics.influxDB.retention: "two_hour"
      metrics.output.frequency.seconds: "10"
      controller.metrics.dynamicCache.size: "2000"
      controller.metrics.statistics.enable: "true"
      controller.metrics.statsD.reporter.enable: "false"
      controller.metrics.statsD.connect.host: "10.109.190.185"
      controller.metrics.statsD.connect.port: "8125"
      controller.metrics.influxDB.reporter.enable: "true"
      controller.metrics.influxDB.connect.uri: "http://192.168.246.24:8086"
      controller.metrics.influxDB.connect.db.name: "pravega"
      controller.metrics.influxDB.retention: "two_hour"
      controller.metrics.output.frequency.seconds: "10"
    longtermStorage:
      filesystem:
        persistentVolumeClaim:
          claimName: {{ .Values.pravega.longtermStorage }}
