name: pravega
version: 0.9.0-2641.0c98b91cd
appVersion: 0.9.0-2641.0c98b91cd
description: pravega Helm chart for Kubernetes
keywords:
- pravega
- storage
home: https://github.com/pravega/pravega
icon: https://avatars3.githubusercontent.com/u/25698199
sources:
- https://github.com/pravega/pravega
engine: gotpl
