name: pravega
version: 0.8.0-2600.4df7f9a4d-1.2-W8-2-e554360
appVersion: 0.8.0-2600.4df7f9a4d-1.2-W8-2-e554360
description: pravega Helm chart for Kubernetes
keywords:
- pravega
- storage
home: https://github.com/pravega/pravega
icon: https://avatars3.githubusercontent.com/u/25698199
sources:
- https://github.com/pravega/pravega
engine: gotpl
