name: pravega
version: 0.8.0-2539.d84a68cc5-1.2-dev-000.5b852dd
appVersion: 0.8.0-2539.d84a68cc5-1.2-dev-000.5b852dd
description: pravega Helm chart for Kubernetes
keywords:
- pravega
- storage
home: https://github.com/pravega/pravega
icon: https://avatars3.githubusercontent.com/u/25698199
sources:
- https://github.com/pravega/pravega
engine: gotpl
