# Default values for pravega.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


version: 0.8.0-2625.f8d5bbb07-r0.8
zookeeperUri: 10.107.135.47:2181
externalAccess:
  enabled: false
  type: LoadBalancer
serviceAccount:
  name: pravega-components
bookkeeperUri: 192.168.219.51:3181
pravega:
  image:
    repository: devops-repo.isus.emc.com:8116/nautilus/pravega
    tag: 0.8.0-2625.f8d5bbb07-r0.8
  controllerReplicas: 2
  segmentStoreReplicas: 8
  debugLogging: false
  cacheVolumeRequest: 20Gi
  storage:
    className: standard
  longtermStorage: pravega-tier2
pravega_resources:
  controller:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 1000m
      memory: 2Gi
  segment_store:
    limits:
      cpu: 4000m
      memory: 5Gi
    requests:
      cpu: 2000m
      memory: 5Gi
debugLogging: true
segmentStoreJVMOptions: ["-Xmx2g", "-XX:MaxDirectMemorySize=2g","-XX:+HeapDumpOnOutOfMemoryError", "-XX:HeapDumpPath=/"]
controllerJvmOptions: ["-Xms512m"]
options:
  bookkeeper.ensemble.size: "3"
  bookkeeper.write.quorum.size: "3"
  bookkeeper.ack.quorum.size: "3"
  bookkeeper.write.timeout.milliseconds: "60000"
  bookkeeper.write.outstanding.bytes.max: "33554432"
  pravegaservice.cache.size.max: "1073741824"
  pravegaservice.cache.time.seconds.max: "600"
  pravegaservice.storage.layout: "CHUNKED_STORAGE"
  writer.flush.threshold.bytes: "67108864"
  writer.flush.size.bytes.max: "67108864"
  pravegaservice.container.count: "64"
  controller.containerCount: "64"
  controller.retention.bucketCount: "8"
  controller.service.asyncTaskPoolSize: "20"
  controller.retention.threadCount: "4"
  log.level: "INFO"
  metrics.dynamicCache.size: "2000"
  metrics.statistics.enable: "true"
  metrics.statsD.reporter.enable: "false"
  metrics.statsD.connect.host: "10.103.131.170"
  metrics.statsD.connect.port: "8125"
  metrics.influxDB.reporter.enable: "true"
  metrics.influxDB.connect.uri: "http://192.168.143.251:8086"
  metrics.influxDB.connect.db.name: "pravega"
  metrics.influxDB.retention: "two_hour"
  metrics.output.frequency.seconds: "10"
  controller.metrics.dynamicCache.size: "2000"
  controller.metrics.statistics.enable: "true"
  controller.metrics.statsD.reporter.enable: "false"
  controller.metrics.statsD.connect.host: "10.103.131.170"
  controller.metrics.statsD.connect.port: "8125"
  controller.metrics.influxDB.reporter.enable: "true"
  controller.metrics.influxDB.connect.uri: "http://192.168.143.251:8086"
  controller.metrics.influxDB.connect.db.name: "pravega"
  controller.metrics.influxDB.retention: "two_hour"
  controller.metrics.output.frequency.seconds: "10"

