# Default values for pravega.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


version: 0.8.0-2539.d84a68cc5-1.2-dev-000.5b852dd
zookeeperUri: zk-client:2181

externalAccess:
  enabled: false
  type: LoadBalancer

serviceAccount:
  name: pravega-components

bookkeeperUri: "pravega-bk-bookie-0.pravega-bk-bookie-headless.default.svc.cluster.local:3181,pravega-bk-bookie-1.pravega-bk-bookie-headless.default.svc.cluster.local:3181,pravega-bk-bookie-2.pravega-bk-bookie-headless.default.svc.cluster.local:3181"

pravega:
  image:
    repository: devops-repo.isus.emc.com:8116/nautilus/nautilus-pravega
    tag: 0.8.0-2539.d84a68cc5-1.2-dev-000.5b852dd
  controllerReplicas: 1
  segmentStoreReplicas: 3
  debugLogging: false
  cacheVolumeRequest: 20Gi
  storage:
    className: standard
  longtermStorage: pravega-tier2
pravega_resources:
  controller:
    limits:
      cpu: 2000m
      memory: 3Gi
    requests:
      cpu: 500m
      memory: 1Gi
  segment_store:
    limits:
      cpu: 8000m
      memory: 10Gi
    requests:
      cpu: 2000m
      memory: 8Gi
controllerJvmOptions: ["-Xms512m"]
segmentStoreJVMOptions: ["-Xmx10g", "-XX:MaxDirectMemorySize=10g"]
options:
  pravegaservice.cacheMaxSize: "6811160064"
pravega_config:
  write_size:
    flushThresholdBytes: "67108864"
pravega_options:
  writer.flushThresholdMillis: "60000"
  extendeds3.smallObjectSizeLimitForConcat: "104857600"
  writer.maxRolloverSizeBytes: "6442450944"
  metrics.dynamicCacheSize: "100000"
  metrics.enableStatistics: "true"
  metrics.enableStatsDReporter: "false"
  metrics.statsdHost: "telegraph.default"
  metrics.statsdPort: "8125"
  metrics.enableInfluxDBReporter: "true"
  metrics.outputFrequencySeconds: "10"
  metrics.influxDBURI: "http://192.168.210.108:8086"
  controller.metrics.dynamicCacheSize: "100000"
  controller.metrics.enableStatistics: "true"
  controller.metrics.enableStatsDReporter: "false"
  controller.metrics.statsdHost: "telegraph.default"
  controller.metrics.statsdPort: "8125"
  controller.metrics.enableInfluxDBReporter: "true"
  controller.metrics.outputFrequencySeconds: "10"
  controller.metrics.influxDBURI: "http://192.168.210.108:8086"
