# Default values for pravega.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


version: 0.8.0-2600.4df7f9a4d-1.2-W8-2-e554360
zookeeperUri: 10.107.135.47:2181
externalAccess:
  enabled: false
  type: LoadBalancer
serviceAccount:
  name: pravega-components
bookkeeperUri: 192.168.219.51:3181
pravega:
  image:
    repository: devops-repo.isus.emc.com:8116/nautilus/pravega
    tag: 0.8.0-2600.4df7f9a4d-1.2-W8-2-e554360
  controllerReplicas: 2
  segmentStoreReplicas: 4
  debugLogging: false
  cacheVolumeRequest: 20Gi
  storage:
    className: standard
  longtermStorage: pravega-tier2
  options:
    metrics:
      influxDB:
        reporterEnable: "false"
        connectUri: http://pravega-influxdb:8086
      statistics:
        enable: "false"
    storage:
      appends:
        enable: "false"
    pravegaservice:
      storage:
        layout: "CHUNKED_STORAGE"
    controller:
      metrics:
        statistics:
          enable: "false"
        influxDB:
          reporterEnable: "false"
          connectUri: http://pravega-influxdb:8086
pravega_resources:
  controller:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 1000m
      memory: 1Gi
  segment_store:
    limits:
      cpu: 2000m
      memory: 6Gi
    requests:
      cpu: 1000m
      memory: 6Gi
debugLogging: true
segmentStoreJVMOptions: ["-Xmx2g", "-XX:MaxDirectMemorySize=3g","-XX:+HeapDumpOnOutOfMemoryError", "-XX:HeapDumpPath=/"]
controllerJvmOptions: ["-Xms512m"]