# Default values for pravega.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


version: 0.8.0-2578.de7f43537
zookeeperUri: 10.107.135.47:2181
externalAccess:
  enabled: false
  type: LoadBalancer
serviceAccount:
  name: pravega-components
bookkeeperUri: 192.168.219.51:3181
pravega:
  image:
    repository: devops-repo.isus.emc.com:8116/nautilus/pravega
    tag: 0.8.0-2578.de7f43537
  controllerReplicas: 1
  segmentStoreReplicas: 3
  debugLogging: false
  cacheVolumeRequest: 20Gi
  storage:
    className: standard
  longtermStorage: pravega-tier2
pravega_resources:
  controller:
    limits:
      cpu: 2000m
      memory: 3Gi
    requests:
      cpu: 2000m
      memory: 3Gi
  segment_store:
    limits:
      cpu: 3000m
      memory: 16Gi
    requests:
      cpu: 2000m
      memory: 16Gi
debugLogging: true
segmentStoreJVMOptions: ["-Xmx4g", "-XX:MaxDirectMemorySize=12g"]
controllerJvmOptions: ["-Xms512m"]
options:
  bookkeeper.bkEnsembleSize: "3"
  bookkeeper.bkWriteQuorumSize: "3"
  bookkeeper.bkAckQuorumSize: "3"
  bookkeeper.bkWriteTimeoutMillis: "60000"
  bookkeeper.maxOutstandingBytes: "33554432"
  pravegaservice.cacheMaxSize: "11811160064"
  pravegaservice.cacheMaxTimeSeconds: "600"
  hdfs.blockSize: "67108864"
  writer.flushThresholdBytes: "67108864"
  writer.maxFlushSizeBytes: "67108864"
  pravegaservice.containerCount: "48"
  controller.containerCount: "48"
  controller.retention.bucketCount: "4"
  controller.service.asyncTaskPoolSize: "20"
  controller.retention.threadCount: "4"
  log.level: "DEBUG"
  metrics.dynamicCache.size: "100000"
  metrics.statistics.enable: "true"
  metrics.statsD.reporter.enable: "true"
  metrics.statsD.connect.host: "telegraph.default"
  metrics.statsD.connect.port: "8125"
  metrics.influxDB.reporter.enable: "true"
  metrics.influxDB.connect.uri: "192.168.219.39:8086"
  metrics.influxDB.connect.db.name: "pravega"
  metrics.influxDB.retention: "two_hour"
  metrics.output.frequency.seconds: "10"
  controller.metrics.dynamicCache.size: "100000"
  controller.metrics.statistics.enable: "true"
  controller.metrics.statsD.reporter.enable: "true"
  controller.metrics.statsD.connect.host: "telegraph.default"
  controller.metrics.statsD.connect.port: "8125"
  controller.metrics.influxDB.reporter.enable: "true"
  controller.metrics.influxDB.connect.uri: "192.168.219.39:8086"
  controller.metrics.influxDB.connect.db.name: "pravega"
  controller.metrics.influxDB.retention: "two_hour"
  controller.metrics.output.frequency.seconds: "10"
