# Default values for pravega.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


version: 0.8.0-2539.d84a68cc5-1.2-dev-000.5b852dd
zookeeperUri: zk-client:2181

externalAccess:
  enabled: false
  type: LoadBalancer

serviceAccount:
  name: pravega-components

bookkeeperUri: "pravega-bk-bookie-0.pravega-bk-bookie-headless.default.svc.cluster.local:3181,pravega-bk-bookie-1.pravega-bk-bookie-headless.default.svc.cluster.local:3181,pravega-bk-bookie-2.pravega-bk-bookie-headless.default.svc.cluster.local:3181"

pravega:
  image:
    repository: devops-repo.isus.emc.com:8116/nautilus/nautilus-pravega
    tag: 0.8.0-2539.d84a68cc5-1.2-dev-000.5b852dd
  controllerReplicas: 1
  segmentStoreReplicas: 9
  debugLogging: false
  cacheVolumeRequest: 20Gi
  storage:
    className: standard
  longtermStorage: pravega-tier2
pravega_resources:
  controller:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi
  segment_store:
    limits:
      cpu: 4000m
      memory: 8Gi
    requests:
      cpu: 1000m
      memory: 8Gi
segmentStoreJVMOptions: ["-Xmx4g", "-XX:MaxDirectMemorySize=4g"]
controllerJvmOptions: ["-Xms512m"]
options:
  bookkeeper.bkEnsembleSize: "3"
  bookkeeper.bkWriteQuorumSize: "3"
  bookkeeper.bkAckQuorumSize: "3"
  bookkeeper.bkWriteTimeoutMillis: "60000"
  bookkeeper.maxOutstandingBytes: "33554432"
  pravegaservice.cacheMaxSize: "3221225472"
  pravegaservice.cacheMaxTimeSeconds: "600"
  hdfs.blockSize: "67108864"
  writer.flushThresholdBytes: "67108864"
  writer.maxFlushSizeBytes: "67108864"
  pravegaservice.containerCount: "16"
  controller.containerCount: "16"
  controller.retention.bucketCount: "4"
  controller.service.asyncTaskPoolSize: "20"
  controller.retention.threadCount: "4"
  log.level: "INFO"
  metrics.dynamicCacheSize: "100000"
  metrics.enableStatistics: "true"
  metrics.enableStatsDReporter: "false"
  metrics.statsdHost: "telegraph.default"
  metrics.statsdPort: "8125"
  metrics.enableInfluxDBReporter: "true"
  metrics.outputFrequencySeconds: "10"
  metrics.influxDBURI: "http://192.168.246.36:8086"
  controller.metrics.dynamicCacheSize: "100000"
  controller.metrics.enableStatistics: "true"
  controller.metrics.enableStatsDReporter: "false"
  controller.metrics.statsdHost: "telegraph.default"
  controller.metrics.statsdPort: "8125"
  controller.metrics.enableInfluxDBReporter: "true"
  controller.metrics.outputFrequencySeconds: "10"
  controller.metrics.influxDBURI: "http://192.168.246.36:8086"
