# Default values for pravega.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


version: 0.8.0-2600.4df7f9a4d-1.2-W8-2-e554360
zookeeperUri: 10.107.135.47:2181
externalAccess:
  enabled: false
  type: LoadBalancer
serviceAccount:
  name: pravega-components
bookkeeperUri: 192.168.219.51:3181
pravega:
  image:
    repository: devops-repo.isus.emc.com:8116/nautilus/pravega
    tag: 0.8.0-2600.4df7f9a4d-1.2-W8-2-e554360
  controllerReplicas: 2
  segmentStoreReplicas: 4
  debugLogging: false
  cacheVolumeRequest: 20Gi
  storage:
    className: standard
  longtermStorage: pravega-tier2
  options:
    metrics:
      influxDB:
        connectUri: http://pravega-influxdb:8086
    controller:
      metrics:
        influxDB:
          connectUri: http://pravega-influxdb:8086
pravega_resources:
  controller:
    limits:
      memory: 1Gi
    requests:
      memory: 1Gi
  segment_store:
    limits:
      memory: 6Gi
    requests:
      memory: 6Gi
debugLogging: true
segmentStoreJVMOptions: ["-Xmx2g", "-XX:MaxDirectMemorySize=3g","-XX:+HeapDumpOnOutOfMemoryError", "-XX:HeapDumpPath=/"]
controllerJvmOptions: ["-Xms512m"]
