# Default values for pravega.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

version: 0.7.0
zookeeperUri: zk-client:2181

externalAccess:
  enabled: false
  type: LoadBalancer

serviceAccount:
  name: pravega-components

bookkeeperUri: "pravega-bk-bookie-0.pravega-bk-bookie-headless.default.svc.cluster.local:3181,pravega-bk-bookie-1.pravega-bk-bookie-headless.default.svc.cluster.local:3181,pravega-bk-bookie-2.pravega-bk-bookie-headless.default.svc.cluster.local:3181"

pravega:
  image:
    repository: pravega/pravega
  controllerReplicas: 1
  segmentStoreReplicas: 1
  debugLogging: false
  cacheVolumeRequest: 20Gi
  storage:
    className: standard
  longtermStorage: pravega-tier2
  pravega_resources:
    controller:
      limits:
        cpu: 2000m
        memory: 3Gi
      requests:
        cpu: 500m
        memory: 1Gi
    segment_store:
      limits:
        cpu: 8000m
        memory: 16Gi
      requests:
        cpu: 2000m
        memory: 4Gi
  controllerJvmOptions: ["-Xms512m"]
  segmentStoreJVMOptions: ["-Xmx4g", "-XX:MaxDirectMemorySize=12g"]
