# Default values for pravega-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: devops-repo.isus.emc.com:8116/nautilus/pravega-operator
  tag: 0.5.2
  pullPolicy: IfNotPresent

## Install RBAC roles and bindings
rbac:
  create: true

## Service account names and whether to create them
serviceAccount:
  create: true
  name: pravega-operator

# Whether to create custom resource
crd:
  create: true

# whether to enable test mode
testmode: false

#
# Specifies which namespace the Operator should watch for new ClusterResource resources
# Default: "" == Watch ALL namespaces
watchNamespace: ""
